name: "Teste de Action"
on: 
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    teste-action-job:
        permissions:
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        name: Execução de Custom Action
        steps: 
            - name: Adicionando Comentário
              uses: niltonppita/action-composite@main
              with:
                GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}
                issue-id: ${{ github.event.issue.number }}
                comment: "Teste de comentário Composite"
            - name: Mostrar o ID do comentário
             run: |
               echo 'ID do comentário é: ${{ steps.commnet_stop.outputs.comment-id }}'


